title: Pradyumna Kumar
logo: /assets/images/headshot.png
description: A seasoned data scientist and machine learning engineer with software development experience. Expertise in Computer Vision, NLP, Deep Learning and MLOps. Writing efficient, scalable and maintainable code in Python, Java and C++. Skilled in building end-to-end machine learning pipelines and deploying scalable models in production environments.
show_download: true
theme: jekyll-theme-minimal
