title: Pradyumna Kumar
logo: assets/images/headshot.jpg
description: Atlanta, GA
**[Email](mailto:pkumar7@students.kennesaw.edu)** | **[LinkedIn](https://www.linkedin.com/in/pradyumnakumar/)**
show_download: true
theme: jekyll-theme-minimal
email: pradyumnakumar@example.com
linkedin: https://www.linkedin.com/in/pradyumnakumar/
